description: >
  CircleCI's Ubuntu-based machine executor VM:
  https://circleci.com/docs/2.0/executor-types/#using-machine
parameters:
  image:
    type: string
    # default: cimg/base:2022.03
    default: ubuntu-2004:202010-01
  use-docker-layer-caching:
    type: boolean
    default: true
  resource-class:
    type: string
    default: medium

# docker:
machine:
  image: <<parameters.image>>

resource_class: <<parameters.resource-class>>
